### ISSUE TITLE
Display bug whith css columns in Chrome

### ISSUE THREAD

**Issue by arnaudjuracek** [kingdido999/zooming#42]
When the image is inside a CSS column layout, the zoomed image stay in the column layout, and the bottom wrap on the next col when the zoomed image is grabbed (which is both weird and awesome).

- OS: OSX
- Browser and version: Chrome 60

### The grid
```scss
.grid {
  column-count: 2;
  column-gap: 1rem;

  figure {
    display: inline-block;
    margin: 0 0 0 0;
    width: 100%;
  }
}
```
![image](https://user-images.githubusercontent.com/2837959/30388778-09ff650e-98b1-11e7-95e1-137db6e0f428.png)

##### last image on the left col
![image](https://user-images.githubusercontent.com/2837959/30389317-c4c52026-98b2-11e7-961a-d335cf6e2110.png)

##### last image on the right col
![image](https://user-images.githubusercontent.com/2837959/30389332-d7254764-98b2-11e7-8d43-5756af7c4078.png)
